<a href="https://colab.research.google.com/github/shubhamlatkar/Stock-Predicition/blob/master/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime
num = [2,3,4,5,3,43,53,1,21,23]
print(num)

[2, 3, 4, 5, 3, 43, 53, 1, 21, 23]


In [0]:
# first = "shubham"
# last = "latkar"

# # print(f'{first} [{last}] is coder')
# msg = "My name is Shubham Latkar"

# print(msg.replace("Shubham ", "Shubham Kiran "))
# print("Shubham" in msg)
# print(len(msg))
# print(msg.title())

# print(10/3)
# print(10//3)
# print(10 % 3)
# print(10 ** 3)
# print(round(2.98))

# has_high_income = True
# has_good_credit = False

# if has_high_income or has_good_credit:
#         print("Eligible")

# if has_high_income and has_good_credit:
#         print("Eligible")

# if has_high_income and not has_good_credit:
#         print("Eligible")

# weight = int(input("Enter weight"))
# unit = input("k for kg and l for pound")

# if unit.upper() == "L":
#     print(weight*0.46)
# else:
#     print(weight//0.46)

# sec_no = 9
# guess_count = 0
# guess_limit = 3

# while guess_count < guess_limit:
#     guess = int(input("Enter guess"))
#     if guess == sec_no:
#             print("you won")
#             break
#     else:
#         guess_count += 1
# else:
#     print("good try")

# for i in range(5,10):
#         print(i)

# print([i for i in range(1,10)])
# print([i*2 for i in range(2,10) if i != 5])
# print([x*y for x in range(2,5) for y in range (3,6)])

# name = "shubham"
# name_list = [l for l in name]
# name_list.append("latkar")
# print(name_list)


# num.sort()
# num.reverse()
# print(num.index(43))
# print(num.count(3))
# print(num)
# uniques = []

# for i in num:
#     if i not in uniques:
#             uniques.append(i)
# uniques.sort()
# print(uniques)

# customer = {
#     "name" : "shubham",
#     "age" : 22,
#     "is_Verified" : True
# }

# print(customer['is_Verified'])

# digits = {
#     "1" : "one",
#     "2" : "two",
#     "3" : "three",
#     "4" : "four"
# }

# ip = input("Enter no")
# op = ""
# for ch in ip:
#     op += digits.get(ch, "!") + " "

# print(op)

# try:
#     age = int(input("Enter no"))
#     print(age)
# except ValueError:
#         print("Invalid")

# print(np.array([1,2,3]))
# print(np.array([[1,2,3],[4,5,6]]))
# print(np.array([1,2,3,4,5,6] ,ndmin = 2))
# a =  np.array([[1,2,3],[4,5,6]])
# a.shape = (3,2)
# print(a)
# a = np.arange(0, 24)
# a = a.reshape(2,4,3)
# print(np.array([1,2,3,4,5]).itemsize)
# a = np.empty([2,2],int)
# print(a)
# a = np.zeros([2,2] , int)
# print(a)
# a = np.ones((2,3) , np.int )
# print(a)

# a = np.asarray(num  ,np.float)
# print(a)

# name = 'shubham'
# a = np.frombuffer(list(name))
# print(a)

a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [0]:
a = np.asarray(num)
a

array([ 2,  3,  4,  5,  3, 43, 53,  1, 21, 23])

In [0]:
a[slice(2,7,2)]

array([ 4,  3, 53])

In [0]:
a[2:7:2]

array([ 4,  3, 53])

In [0]:
a[2]
a[2:]

array([ 4,  5,  3, 43, 53,  1, 21, 23])

In [0]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a[-1:]

array([[4, 5, 6]])

In [0]:
a[...,1]
a[1,...]

array([3, 4, 5])

In [0]:
x = np.array([[0,1,2] , [3,4,5] , [11,44,65] , [43,65,87]])
x[1:3,1:3]

array([[ 4,  5],
       [44, 65]])

In [0]:
x[1:3,[0]]

array([[ 3],
       [11]])

In [0]:
x[x>5]

array([11, 44, 65, 43, 65, 87])

In [0]:
x[~np.isnan(x)]

array([ 0,  1,  2,  3,  4,  5, 11, 44, 65, 43, 65, 87])

In [0]:
a = []
for i in np.nditer(x):
    a.append(i)
print(a)    

[array(0), array(1), array(2), array(3), array(4), array(5), array(11), array(44), array(65), array(43), array(65), array(87)]


In [0]:
x.T

array([[ 0,  3, 11, 43],
       [ 1,  4, 44, 65],
       [ 2,  5, 65, 87]])

In [0]:
print(x)
for i in np.nditer(x , op_flags=['readwrite']):
  i[...] = 2*i
  
print(x)  

[[ 0  1  2]
 [ 3  4  5]
 [11 44 65]
 [43 65 87]]
[[  0   2   4]
 [  6   8  10]
 [ 22  88 130]
 [ 86 130 174]]


In [0]:
y = np.arange(0,45,5)
y = y.reshape(3,3)
print(y)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [0]:
for i,j in np.nditer([x,y]):
  print("hi")

ValueError: ignored

In [0]:
y = np.append(y , [[2,3,4]] , axis = 0)
print(y)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [ 2  3  4]]


In [0]:
cd ..

/


In [0]:
ls

bin/      dev/   lib32/  opt/   sbin/   tensorflow-2.0.0a0/  var/
boot/     etc/   lib64/  proc/  srv/    tmp/
content/  home/  media/  root/  swift/  tools/
datalab/  lib/   mnt/    run/   sys/    usr/


In [0]:
cd bin

SyntaxError: ignored

In [0]:
ls

bash*           journalctl*     sync*
bunzip2*        kill*           systemctl*
bzcat*          kmod*           systemd@
bzcmp@          less*           systemd-ask-password*
bzdiff*         lessecho*       systemd-escape*
bzegrep@        lessfile@       systemd-hwdb*
bzexe*          lesskey*        systemd-inhibit*
bzfgrep@        lesspipe*       systemd-machine-id-setup*
bzgrep*         ln*             systemd-notify*
bzip2*          login*          systemd-sysusers*
bzip2recover*   loginctl*       systemd-tmpfiles*
bzless@         ls*             systemd-tty-ask-password-agent*
bzmore*         lsblk*          tar*
cat*            lsmod@          tempfile*
chgrp*          mkdir*          touch*
chmod*          mknod*          true*
chown*          mktemp*         udevadm*
cp*             more*           ulockmgr_server*
dash*           mount*          umount*
date*           mountpoint*     uname*
dd*             mv*             uncompress*
df*             networkctl*     vdir*
dir*

In [0]:
cd dash

[Errno 20] Not a directory: 'dash'
/bin


In [0]:
cd ..

/


In [0]:
ls

bin/      dev/   lib32/  opt/   sbin/   tensorflow-2.0.0a0/  var/
boot/     etc/   lib64/  proc/  srv/    tmp/
content/  home/  media/  root/  swift/  tools/
datalab/  lib/   mnt/    run/   sys/    usr/


In [0]:
cd tmp

/tmp


In [0]:
cd ..

/


In [0]:
cd tensorflow-2.0.0a0/

/tensorflow-2.0.0a0


In [0]:
ls

python2.7/  python3.6/


In [0]:
cd ..

/


In [0]:
top

NameError: ignored

In [0]:
ip-config

NameError: ignored

In [0]:
cd content

/content


In [0]:
ls

sample_data/


In [0]:

a = np.array([1,2,3,4])
s = pd.Series(a)
print(s)

NameError: ignored

In [0]:
s = pd.Series(a , index=[101,102,103,104])
print(s)

101    1
102    2
103    3
104    4
dtype: int64


In [0]:
s = pd.Series(5 , index = ['a','b','c','d','e'])

In [0]:
print(s)

a    5
b    5
c    5
d    5
e    5
dtype: int64


In [0]:
print(s[:3])
print(s[-3:])
print(s['c'])

a    5
b    5
c    5
dtype: int64
c    5
d    5
e    5
dtype: int64
5


In [0]:
d = [['shu',1],['ku',2],['ath',3]]
df = pd.DataFrame(d , columns = ['Name', 'num'])
print(df)

  Name  num
0  shu    1
1   ku    2
2  ath    3


In [0]:
d = {'Names' : ['shu' , 'ku' , 'ath'] , 'age' : [21,21,22]}
df = pd.DataFrame(d , index = ['rank1' , 'rank2' , 'rank3'])

In [0]:
print(df)

      Names  age
rank1   shu   21
rank2    ku   21
rank3   ath   22


In [0]:
d = [{'a' : 1 , 'b' : 2},  {'a' : 1  ,'b' : 2 , 'c' : 4}]
df = pd.DataFrame(d , index = ['first' , 'second'])

In [0]:
print(df)

        a  b    c
first   1  2  NaN
second  1  2  4.0


In [0]:
df = pd.DataFrame(d , index = ['first' , 'second'] , columns=['a' , 'b'])

In [0]:
print(df)

        a  b
first   1  2
second  1  2


In [0]:
df = pd.DataFrame(d , index = ['first' , 'second'] , columns=['a','b1'])

In [0]:
print(df)

        a  b1
first   1 NaN
second  1 NaN


In [0]:
del(df['a'])

In [0]:
print(df)

        b    c
first   2  NaN
second  2  4.0


In [0]:
df.pop('c')

NameError: ignored

In [0]:
print(df)

        a  b    c
first   1  2  NaN
second  1  2  4.0


In [0]:
print(df.loc['first'])

a    1.0
b    2.0
c    NaN
Name: first, dtype: float64


In [0]:
print(df.iloc[[1] , :])

        a  b    c
second  1  2  4.0


In [0]:
dataset = web.DataReader('aapl' , 'yahoo' ,datetime(2018,11,1),datetime.now())


In [0]:
print(dataset.tail())

                  High         Low  ...      Volume   Adj Close
Date                                ...                        
2019-06-06  185.470001  182.149994  ...  22526300.0  185.220001
2019-06-07  191.919998  185.770004  ...  30684400.0  190.149994
2019-06-10  195.369995  191.619995  ...  26220900.0  192.580002
2019-06-11  196.000000  193.600006  ...  26932900.0  194.809998
2019-06-12  195.970001  193.389999  ...  18221800.0  194.190002

[5 rows x 6 columns]


In [0]:
a = np.array(dataset['Close'])

In [0]:
print(a[-10:])

[178.30000305 175.07000732 173.30000305 179.63999939 182.53999329
 185.22000122 190.1499939  192.58000183 194.80999756 194.19000244]


In [0]:
df = dataset['Close']
print(df.ndim)

1


In [0]:
print(dataset.ndim)

2


In [0]:
print(dataset.size)

912


In [0]:
len(dataset)

152

In [0]:
# print(np.array([1,2,3,4,5,6] ,ndmin = 2))
a = np.asarray(dataset['Close'].values)
a = np.array(a , ndmin = 2)
# print(a)
for i in a[0][-10:]:
  print((i))

178.3000030517578
175.07000732421875
173.3000030517578
179.63999938964844
182.5399932861328
185.22000122070312
190.14999389648438
192.5800018310547
194.80999755859375
194.19000244140625


In [0]:
import pandas_datareader.data as web
from datetime import datetime
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM 

from sklearn.preprocessing import StandardScaler ,  MinMaxScaler
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [0]:
ewma = pd.Series.ewm
dataset = web.DataReader('aapl' , 'yahoo' ,datetime(2018,1,1),datetime.now())
dataset['H-L'] = dataset['High'] - dataset['Low']
dataset['O-C'] = dataset['Close'] - dataset['Open']
dataset['3day MA'] = dataset['Close'].shift(1).rolling(window = 3).mean()
dataset['10day MA'] = dataset['Close'].shift(1).rolling(window = 10).mean()
dataset['30day MA'] = dataset['Close'].shift(1).rolling(window = 30).mean()
dataset['Std_dev']= dataset['Close'].rolling(5).std()
dataset['Price_Rise'] = np.where(dataset['Close'].shift(-1) > dataset['Close'], 1, 0)
# dataset['ma7'] = dataset['Close'].rolling(window=7).mean()
# dataset['ma21'] = dataset['Close'].rolling(window=21).mean()

# # Create MACD
# dataset['26ema'] = pd.DataFrame.ewm(dataset['Close'], span=26).mean()
# dataset['12ema'] = pd.DataFrame.ewm(dataset['Close'], span=12).mean()
# dataset['MACD'] = (dataset['12ema']-dataset['26ema'])

# # Create Bollinger Bands
# dataset['20sd'] = dataset['Close'].rolling(20).std()
# dataset['upper_band'] = dataset['ma21'] + (dataset['20sd']*2)
# dataset['lower_band'] = dataset['ma21'] - (dataset['20sd']*2)

# # Create Exponential moving average
# dataset['ema'] = dataset['Close'].ewm(com=0.5).mean()

# # Create Momentum
# dataset['momentum'] = dataset['Close']-1
dataset = dataset.dropna()

In [0]:
dataset.head()

High         Low  ...   Std_dev  Price_Rise
Date                                ...                      
2018-02-14  167.539993  162.880005  ...  5.238203           1
2018-02-15  173.089996  169.000000  ...  6.096029           0
2018-02-16  174.820007  171.770004  ...  4.644794           0
2018-02-20  174.259995  171.419998  ...  3.775315           0
2018-02-21  174.119995  171.009995  ...  2.225339           1

[5 rows x 13 columns]

In [0]:
# scaler = StandardScaler()
# d1 = np.array(dataset['Close'], ndmin =2 )
# print(d1)
# data = scaler.fit_transform(dataset['Close'])

X = dataset.iloc[:, 5:-1]
y = dataset.iloc[:, [3]]

split = int(len(dataset)*0.8)
X_train, X_test, y_train, y_test = X[:split], X[split:], y[:split], y[split:]
X_test.head()



Adj Close       H-L       O-C  ...    10day MA    30day MA   Std_dev
Date                                        ...                                  
2019-03-12  180.215988  3.300003  0.910004  ...  174.753000  171.022666  3.758093
2019-03-13  181.012924  2.380005 -0.539993  ...  175.411000  171.842999  4.396457
2019-03-14  183.025162  1.540009 -0.169998  ...  176.095001  172.744000  4.137210
2019-03-15  185.406006  3.589996  1.269989  ...  177.153001  173.360000  2.760167
2019-03-18  187.298721  2.600006  2.220001  ...  178.268001  174.015999  2.977912

[5 rows x 7 columns]

In [0]:
X_test.shape

(67, 6)

In [0]:
# split into train and test sets
# train_size = int(len(dataset) * 0.67)
# test_size = len(dataset) - train_size
# train, test = data[0:train_size,:], data[train_size:len(data),:]
# print(len(train), len(test))

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train[-1:])

[[-0.29412367  0.03701349  1.36927216 -0.62228778 -0.5715     -0.79148077
  -0.13659588]]


In [0]:
X_train = np.reshape(X_train , ( X_train.shape[0] , 1  , X_train.shape[1]))
X_test = np.reshape(X_test , ( X_test.shape[0] , 1  , X_test.shape[1]))

In [0]:
model = Sequential()
model.add(LSTM(30, input_shape=(1, 7)))

model.add(Dense(1 , activation='relu'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=200, batch_size=1, verbose=2)

Epoch 1/200
 - 2s - loss: 35200.1216
Epoch 2/200
 - 1s - loss: 34116.3899
Epoch 3/200
 - 1s - loss: 32178.0718
Epoch 4/200
 - 1s - loss: 30293.6193
Epoch 5/200
 - 1s - loss: 28532.7073
Epoch 6/200
 - 1s - loss: 26775.3393
Epoch 7/200
 - 1s - loss: 24992.1745
Epoch 8/200
 - 1s - loss: 23145.3689
Epoch 9/200
 - 1s - loss: 21109.5715
Epoch 10/200
 - 1s - loss: 18794.7733
Epoch 11/200
 - 1s - loss: 16378.8975
Epoch 12/200
 - 1s - loss: 14127.9529
Epoch 13/200
 - 1s - loss: 12096.1141
Epoch 14/200
 - 1s - loss: 10342.4933
Epoch 15/200
 - 1s - loss: 8963.7052
Epoch 16/200
 - 1s - loss: 7890.4513
Epoch 17/200
 - 1s - loss: 6966.0993
Epoch 18/200
 - 1s - loss: 6138.8159
Epoch 19/200
 - 1s - loss: 5392.0396
Epoch 20/200
 - 1s - loss: 4717.1745
Epoch 21/200
 - 1s - loss: 4109.4472
Epoch 22/200
 - 1s - loss: 3563.9582
Epoch 23/200
 - 1s - loss: 3075.8298
Epoch 24/200
 - 1s - loss: 2642.4500
Epoch 25/200
 - 1s - loss: 2262.3424
Epoch 26/200
 - 1s - loss: 1930.2246
Epoch 27/200
 - 1s - loss: 1642.2

In [0]:
testPredict = model.predict(X_test)
print(testPredict[-10:])

[[173.36502]
 [180.10248]
 [182.56593]
 [191.60078]
 [196.04886]
 [200.51222]
 [199.72365]
 [195.7461 ]
 [193.77147]
 [194.09123]]


In [0]:
print(y_test.iloc[-10: , :])

                 Close
Date                  
2019-06-03  173.300003
2019-06-04  179.639999
2019-06-05  182.539993
2019-06-06  185.220001
2019-06-07  190.149994
2019-06-10  192.580002
2019-06-11  194.809998
2019-06-12  194.190002
2019-06-13  194.149994
2019-06-14  192.740005


In [0]:
print(y_test.columns)

Index(['Close'], dtype='object')


In [0]:
print(mean_squared_error(testPredict , y_test['Close']))

17.49012703329686


In [0]:
\